Add dependency handling + code cleanup
Aurtool can now handle installing package dependencies from AUR recursively. Also cleaned up the code a bit.

diff --git a/aurtool b/aurtool
--- a/aurtool
+++ b/aurtool
@@ -1,8 +1,8 @@
 #!/usr/bin/env bash
 
 #
-#  Aurtool V0.1.3 beta
-#  
+#  Aurtool V0.2 beta
+#
 #  Maintainer: Eris Nihila (M1ndFlay3r)
 #              sp0t1fyfr33tr1alabus3@outlook.com
 #
@@ -21,6 +21,41 @@
 OP=$1
 USR="$(whoami)"
 
+#library functions borrowed from lemonlib
+function isyes {
+  if [ ! -z "$1" ]; then
+    read -p "$1  " ANSWER
+  else
+    read ANSWER
+  fi
+  if [ -z "$ANSWER" ]; then
+    ANSWER="y"
+  fi
+  if [ $ANSWER == y ] || [ $ANSWER == Y ] || [ $ANSWER == yes ] || [ $ANSWER == Yes ] || [ $ANSWER == YES ]; then
+    yes=0 && return 0
+  else
+    yes=1 && return 1
+  fi
+}
+
+function isvalidresponse {
+  if [ -z "$OP" ]; then
+    OP="NULL"
+  fi
+  for i in "${VALID[@]}"; do
+    if echo "$i" | grep "$OP" &> /dev/null; then
+      return 0
+    fi
+  done
+}
+
+#script body
+VALID=("-S" "-Sy" "-Syu" "-Ss" "--help" "-Syyu" "-Sss" "--version")
+if ! isvalidresponse; then
+  echo "Invalid command!"
+  echo "--help for help"
+  exit 1
+fi
 
 if [ "$USR" == root ]; then
   echo "Error: aurtool cannot be run as root!"
@@ -28,10 +63,20 @@ if [ "$USR" == root ]; then
 fi
 
 if [ "$OP" == -Ss ]; then
+  if [ -z ${@:2} ]; then
+    echo "Error: -Ss requires additional input."
+    echo "aurtool --help for help page"
+    exit 1
+  fi
   package-query -A -s ${@:2}
 fi
 
 if [ "$OP" == -Sss ]; then
+  if [ -z ${@:2} ]; then
+    echo "Error: -Sss requires additional input."
+    echo "aurtool --help for help page"
+    exit 1
+  fi
   echo "-"
   echo "Non-AUR"
   echo "-"
@@ -43,6 +88,11 @@ if [ "$OP" == -Sss ]; then
 fi
 
 if [ "$OP" == -S ]; then
+  if [ -z ${@:2} ]; then
+    echo "Error: -S requires additional input."
+    echo "aurtool --help for help page"
+    exit 1
+  fi
   for b in ${@:2}; do
     cd $HOME
     mkdir .aurtool
@@ -55,10 +105,11 @@ if [ "$OP" == -S ]; then
       echo "Aborting"
       exit 1
     fi
-    echo "Would you like to edit the PKGBUILD? (Y/n)"
-    read ANSWER
+    #
+    # Yes, this is a pointless function that uses up 3 lines unnecessarily. The script didn't behave properly without it. Bash has moods, and Brian Fox hates us all.
+    #
     function PKGBUILD {
-    if [ $ANSWER == y ] || [ $ANSWER == Y ] || [ $ANSWER == Yes ] || [ $ANSWER == yes ] || [ $ANSWER == YES ]; then
+    if isyes "Would you like to edit the PKGBUILD? (Y/n)" ; then
       if which nano &> /dev/null; then
         nano ./PKGBUILD
       else
@@ -67,7 +118,6 @@ if [ "$OP" == -S ]; then
         else
           echo "No suitable text editor found!"
           echo "If one is present on the system, enter its command now (eg: nano, vim, emacs, etc). Otherwise leave blank to skip PKGBUILD editing."
-          unset PKGEDIT
           read PKGEDIT
           if [ -v $PKGEDIT ]; then 
             $PKGEDIT ./PKGBUILD
@@ -77,19 +127,45 @@ if [ "$OP" == -S ]; then
     fi
     }
     PKGBUILD
-    makepkg -csi
-    if [ $? -eq 1 ]; then
+    unset makedepends
+    unset optdepends
+    unset depends
+    source ./PKGBUILD
+    uDEPS=(${makedepends[@]} ${depends[@]})
+    for i in ${uDEPS[@]}; do
+      i=${i%=*}
+      i=${i%>*}
+      i=${i%<*}
+      DEPS=(${DEPS[@]} $i)
+    done
+    for i in ${DEPS[@]}; do
+      if ! pacman -Ql $i &> /dev/null; then
+        echo "Trying to install $i with pacman (dependency)"
+        if ! sudo pacman -S --noconfirm --needed $i; then
+          echo "Installing $i with pacman failed"
+          echo "Trying to install $i from AUR"
+          if ! NODEL=1 aurtool -S $i; then
+            echo "FATAL: Unable to install dependency $i!"
+            exit 1
+          fi
+        fi
+      fi
+    done
+    if ! makepkg -csi; then
       echo "Error! Aborting"
-      cd $HOME/.aurtool
+      cd $HOME
       exit 1
     fi
     cd $HOME/.aurtool
   done
-  echo "Build files and / or built packages are stored in .aurtool in your home directory. Would you like to delete them? "
-  read ANSWER
-  if [ $ANSWER == y ] || [ $ANSWER == Y ] || [ $ANSWER == yes ] || [ $ANSWER == Yes ] || [ $ANSWER == YES ]; then
-    echo "Cleaning up.."
-    rm -rf $HOME/.aurtool
+  if [ -z "$NODEL" ]; then
+    NODEL="0"
+  fi
+  if [ ! "$NODEL" == 1 ]; then
+    if isyes "Build files and / or built packages are stored in .aurtool in your home directory. Would you like to delete them? (Y/n)"; then
+      echo "Cleaning up.."
+      rm -rf $HOME/.aurtool
+    fi
   fi
 fi
 
@@ -99,6 +175,10 @@ fi
 
 if [ "$OP" == -Syu ]; then
   UPD=$(package-query -A -u | grep -oP "aur/\K[^ ]*")
+  if [ -z "$UPD" ]; then
+    echo "There is nothing to do"
+    exit 0
+  fi
   for i in $UPD; do
     aurtool -S $i
   done
@@ -112,7 +192,7 @@ if [ "$OP" == -Syyu ]; then
 fi
 
 if [ "$OP" == --version ]; then
-  echo "aurtool V0.1.3 beta"
+  echo "aurtool V0.2 beta"
 fi
 
 if [ "$OP" == --help ]; then
@@ -128,11 +208,5 @@ if [ "$OP" == --help ]; then
   echo " -Sss   - search both repositories and AUR for package by name"
   echo " --help - display this help dialog"
   echo " ------------------------------------------------------"
-fi
-
-if [ ! "$OP" == -S ] && [ ! "$OP" == -Sy ] && [ ! "$OP" == -Syu ] && [ ! "$OP" == -Ss ] && [ ! "$OP" == --help ] && [ ! "$OP" == -Syyu ] && [ ! "$OP" == -Sss ] && [ ! "$OP" == --version ]; then
-  echo "Invalid command!"
-  echo "--help for help"
-  exit 1
 fi
 
